# Site settings
title:            "Kevin's Awful Website"
# tagline:          "by Kevin Rohrbaugh"
description:      "Made by a programmer and gamer in San Francisco."
url:              "http://kevinsawful.website"
baseurl:          ""
paginate:         5
jquery-version:   "2.1.3"
ga-identifier:    "UA-61801088-1"

# Author settings
author:
  name:           "Kevin Rohrbaugh"
  email:          "kevin+blog@rhrbgh.com"
  twitter:        "https://twitter.com/krohrbaugh"
  github:         "https://github.com/krohrbaugh"
  linkedin:       "https://www.linkedin.com/in/krohrbaugh"
  steam:          "http://steamcommunity.com/id/krohrbaugh"

# Build settings
markdown:         redcarpet
highlighter:      pygments
permalink:        pretty
plugins:
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - script
  - s3_website.yml

kramdown:
  input: GFM

assets:
  css_compressor: sass
  js_compressor: uglifier
  sources:
    - _assets/images
    - _assets/images/posts
    - _assets/javascripts
    - _assets/stylesheets
