# Site settings
title:            "Soggy Cupcakes"
tagline:          "by Kevin Rohrbaugh"
description:      "Made by a programmer and gamer in San Francisco."
url:              "http://soggycupcakes.com"
baseurl:          "/"
paginate:         5

# Author settings
author:
  name:           "Kevin Rohrbaugh"
  email:          "kevin+blog@rhrbgh.com"

# Build settings
markdown:         kramdown
highlighter:      pygments
permalink:        pretty
